name: Build

on:
  workflow-call:

env:
  GO_VERSION: '1.21'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Setup buf action
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Get tools dependencies
      run: make tools

    - name: Lint
      run: make lint

    - name: Lint proto files
      uses: bufbuild/buf-lint-action@v1

    - name: Build
      run: make build

    - name: Stack
      run: docker compose -f build/docker/docker-compose.yml up --build -d

    - name: Test
      run: go test -tags integration -race -coverprofile=coverage.txt -covermode=atomic -v ./...

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
