name: Bench

on:
  workflow_call:
  pull_request:
    branches: [ main ]
    paths:
      - 'pkg/**'
      - 'server/packs/**'

env:
  GO_VERSION: '1.21'

jobs:
  bench:
    name: bench
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

    - name: Set up Go ${{ env.GO_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Check out code
      uses: actions/checkout@v4

    - name: Get tools dependencies
      run: make tools

    - name: Stack
      run: docker compose -f build/docker/docker-compose.yml up --build -d

    - name: Bench
      run: make bench

    - name: Download previous benchmark data
      uses: actions/cache@v3
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
      with:
        name: Go Benchmark
        tool: 'go'
        output-file-path: output.txt
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: false
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-always: true
