name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'api/docs/**'
      - 'build/charts/**'
      - '**/*.md'
      - '**/*.txt'
      - '**/.gitignore'

env:
  GO_VERSION: '1.21'

jobs:
  build:
    uses: ./.github/workflows/ci/build-job.yml

  bench:
    uses: ./.github/workflows/ci/bench-job.yml

  sharding_test:
    uses: ./.github/workflows/ci/sharding-test-job.yml
